### ISSUE TITLE
On Death Inventory - Crafting Box Bug. Inventory not fully cleared.

### ISSUE THREAD

**Issue by ghost** [mixxit/MixxitPlugin#1]
Inside your inventory, next to the portrait of your character, there's 4 crafting boxes - if you are killed, the stuff in those boxes stays with you.

**Comment by mixxit** [comment]
are these higher inventory slot id's?

for (int slot = 0; slot < 36; slot++)

perhaps we need > 36?

**Comment by ghost** [comment]
i believe they are. Not exactly 100% sure. It's something I was going to play around with and do some testing, but just haven't had the time to do so. 

Moving from one place to a different apartment and having to pack everything up has left me tired the last two days. I hoping to did into the stat system this coming week when everything calms down and I get settled in.
